// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: token20.proto

package entity

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//函数操作类型：{
//1.transfers(address to[], uint256 value[]) public returns (bool);
//2.Deprecated transferFrom(address from, address to[], uint256 value[]) public returns (bool);//
//3.Deprecated approve(address to[], uint256 value[]) public returns (bool);
//4.print(address to[],uint256 value[]) public returns(bool);
//5.burn(uint value) public returns(bool);销毁
//6.construct_fixSupply(address to[],uint256 []values) public returns (bool);创建合约
//7.construct_printable(address to[],uint256 []values,bytes exdatas) public returns (bool);创建合约
//8.addManagers(address to[]);
//9.rmManagers(address to[]);
//}
type ContractRC20_Function20 int32

const (
	ContractRC20_UNKNOW              ContractRC20_Function20 = 0
	ContractRC20_CONSTRUCT_FIXSUPPLY ContractRC20_Function20 = 1
	ContractRC20_CONSTRUCT_PRINTABLE ContractRC20_Function20 = 2
	ContractRC20_TRANSFERS           ContractRC20_Function20 = 3
	ContractRC20_PRINT               ContractRC20_Function20 = 4
	ContractRC20_BURN                ContractRC20_Function20 = 5
	ContractRC20_ADDMANAGERS         ContractRC20_Function20 = 6
	ContractRC20_RMMANAGERS          ContractRC20_Function20 = 7
)

// Enum value maps for ContractRC20_Function20.
var (
	ContractRC20_Function20_name = map[int32]string{
		0: "UNKNOW",
		1: "CONSTRUCT_FIXSUPPLY",
		2: "CONSTRUCT_PRINTABLE",
		3: "TRANSFERS",
		4: "PRINT",
		5: "BURN",
		6: "ADDMANAGERS",
		7: "RMMANAGERS",
	}
	ContractRC20_Function20_value = map[string]int32{
		"UNKNOW":              0,
		"CONSTRUCT_FIXSUPPLY": 1,
		"CONSTRUCT_PRINTABLE": 2,
		"TRANSFERS":           3,
		"PRINT":               4,
		"BURN":                5,
		"ADDMANAGERS":         6,
		"RMMANAGERS":          7,
	}
)

func (x ContractRC20_Function20) Enum() *ContractRC20_Function20 {
	p := new(ContractRC20_Function20)
	*p = x
	return p
}

func (x ContractRC20_Function20) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContractRC20_Function20) Descriptor() protoreflect.EnumDescriptor {
	return file_token20_proto_enumTypes[0].Descriptor()
}

func (ContractRC20_Function20) Type() protoreflect.EnumType {
	return &file_token20_proto_enumTypes[0]
}

func (x ContractRC20_Function20) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContractRC20_Function20.Descriptor instead.
func (ContractRC20_Function20) EnumDescriptor() ([]byte, []int) {
	return file_token20_proto_rawDescGZIP(), []int{0, 0}
}

type ContractRC20 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Function ContractRC20_Function20 `protobuf:"varint,1,opt,name=function,proto3,enum=entity.ContractRC20_Function20" json:"function,omitempty"` //
	From     []byte                  `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Tos      [][]byte                `protobuf:"bytes,3,rep,name=tos,proto3" json:"tos,omitempty"`
	Values   [][]byte                `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`
	ExtDatas []byte                  `protobuf:"bytes,6,opt,name=ext_datas,json=extDatas,proto3" json:"ext_datas,omitempty"` //扩展信息
	Name     string                  `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`                        //构建函数时候使用
	Symbol   string                  `protobuf:"bytes,11,opt,name=symbol,proto3" json:"symbol,omitempty"`                    //构建函数时候使用
	Decimals int64                   `protobuf:"varint,12,opt,name=decimals,proto3" json:"decimals,omitempty"`               //精度构建函数时候使用
}

func (x *ContractRC20) Reset() {
	*x = ContractRC20{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token20_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractRC20) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractRC20) ProtoMessage() {}

func (x *ContractRC20) ProtoReflect() protoreflect.Message {
	mi := &file_token20_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractRC20.ProtoReflect.Descriptor instead.
func (*ContractRC20) Descriptor() ([]byte, []int) {
	return file_token20_proto_rawDescGZIP(), []int{0}
}

func (x *ContractRC20) GetFunction() ContractRC20_Function20 {
	if x != nil {
		return x.Function
	}
	return ContractRC20_UNKNOW
}

func (x *ContractRC20) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ContractRC20) GetTos() [][]byte {
	if x != nil {
		return x.Tos
	}
	return nil
}

func (x *ContractRC20) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ContractRC20) GetExtDatas() []byte {
	if x != nil {
		return x.ExtDatas
	}
	return nil
}

func (x *ContractRC20) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContractRC20) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ContractRC20) GetDecimals() int64 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

type TokenRC20Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance string `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Locked  string `protobuf:"bytes,2,opt,name=locked,proto3" json:"locked,omitempty"`
	ExtData string `protobuf:"bytes,3,opt,name=ext_data,json=extData,proto3" json:"ext_data,omitempty"`
}

func (x *TokenRC20Value) Reset() {
	*x = TokenRC20Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token20_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenRC20Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRC20Value) ProtoMessage() {}

func (x *TokenRC20Value) ProtoReflect() protoreflect.Message {
	mi := &file_token20_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRC20Value.ProtoReflect.Descriptor instead.
func (*TokenRC20Value) Descriptor() ([]byte, []int) {
	return file_token20_proto_rawDescGZIP(), []int{1}
}

func (x *TokenRC20Value) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *TokenRC20Value) GetLocked() string {
	if x != nil {
		return x.Locked
	}
	return ""
}

func (x *TokenRC20Value) GetExtData() string {
	if x != nil {
		return x.ExtData
	}
	return ""
}

type TokenRC20Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Creator         []byte   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"` //创建者
	CreateTime      int64    `protobuf:"varint,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	TotalSupply     []byte   `protobuf:"bytes,3,opt,name=totalSupply,proto3" json:"totalSupply,omitempty"` //总量
	Managers        [][]byte `protobuf:"bytes,4,rep,name=managers,proto3" json:"managers,omitempty"`       //管理员
	Name            string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Symbol          string   `protobuf:"bytes,6,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals        int64    `protobuf:"varint,7,opt,name=decimals,proto3" json:"decimals,omitempty"` //精度
	ExtDatas        []byte   `protobuf:"bytes,8,opt,name=ext_datas,json=extDatas,proto3" json:"ext_datas,omitempty"`
	Printable       bool     `protobuf:"varint,9,opt,name=printable,proto3" json:"printable,omitempty"`             //是否可以增发
	StorageTrieRoot []byte   `protobuf:"bytes,10,opt,name=storageTrieRoot,proto3" json:"storageTrieRoot,omitempty"` //存储根
}

func (x *TokenRC20Info) Reset() {
	*x = TokenRC20Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token20_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenRC20Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRC20Info) ProtoMessage() {}

func (x *TokenRC20Info) ProtoReflect() protoreflect.Message {
	mi := &file_token20_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRC20Info.ProtoReflect.Descriptor instead.
func (*TokenRC20Info) Descriptor() ([]byte, []int) {
	return file_token20_proto_rawDescGZIP(), []int{2}
}

func (x *TokenRC20Info) GetCreator() []byte {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *TokenRC20Info) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *TokenRC20Info) GetTotalSupply() []byte {
	if x != nil {
		return x.TotalSupply
	}
	return nil
}

func (x *TokenRC20Info) GetManagers() [][]byte {
	if x != nil {
		return x.Managers
	}
	return nil
}

func (x *TokenRC20Info) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TokenRC20Info) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TokenRC20Info) GetDecimals() int64 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *TokenRC20Info) GetExtDatas() []byte {
	if x != nil {
		return x.ExtDatas
	}
	return nil
}

func (x *TokenRC20Info) GetPrintable() bool {
	if x != nil {
		return x.Printable
	}
	return false
}

func (x *TokenRC20Info) GetStorageTrieRoot() []byte {
	if x != nil {
		return x.StorageTrieRoot
	}
	return nil
}

type ReqCall20Contract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ContractRC20 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ReqCall20Contract) Reset() {
	*x = ReqCall20Contract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token20_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqCall20Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCall20Contract) ProtoMessage() {}

func (x *ReqCall20Contract) ProtoReflect() protoreflect.Message {
	mi := &file_token20_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCall20Contract.ProtoReflect.Descriptor instead.
func (*ReqCall20Contract) Descriptor() ([]byte, []int) {
	return file_token20_proto_rawDescGZIP(), []int{3}
}

func (x *ReqCall20Contract) GetData() *ContractRC20 {
	if x != nil {
		return x.Data
	}
	return nil
}

type RespCall20Contract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datas      []byte `protobuf:"bytes,1,opt,name=datas,proto3" json:"datas,omitempty"`
	RetCode    int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	RetMessage string `protobuf:"bytes,3,opt,name=ret_message,json=retMessage,proto3" json:"ret_message,omitempty"`
}

func (x *RespCall20Contract) Reset() {
	*x = RespCall20Contract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token20_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespCall20Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespCall20Contract) ProtoMessage() {}

func (x *RespCall20Contract) ProtoReflect() protoreflect.Message {
	mi := &file_token20_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespCall20Contract.ProtoReflect.Descriptor instead.
func (*RespCall20Contract) Descriptor() ([]byte, []int) {
	return file_token20_proto_rawDescGZIP(), []int{4}
}

func (x *RespCall20Contract) GetDatas() []byte {
	if x != nil {
		return x.Datas
	}
	return nil
}

func (x *RespCall20Contract) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *RespCall20Contract) GetRetMessage() string {
	if x != nil {
		return x.RetMessage
	}
	return ""
}

type ReqQueryRC20TokenInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenAddress []byte `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
}

func (x *ReqQueryRC20TokenInfo) Reset() {
	*x = ReqQueryRC20TokenInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token20_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqQueryRC20TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqQueryRC20TokenInfo) ProtoMessage() {}

func (x *ReqQueryRC20TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_token20_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqQueryRC20TokenInfo.ProtoReflect.Descriptor instead.
func (*ReqQueryRC20TokenInfo) Descriptor() ([]byte, []int) {
	return file_token20_proto_rawDescGZIP(), []int{5}
}

func (x *ReqQueryRC20TokenInfo) GetTokenAddress() []byte {
	if x != nil {
		return x.TokenAddress
	}
	return nil
}

type RespQueryRC20TokenInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenAddress []byte         `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Info         *TokenRC20Info `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	TokenNonce   int32          `protobuf:"varint,3,opt,name=token_nonce,json=tokenNonce,proto3" json:"token_nonce,omitempty"`
	RetCode      int32          `protobuf:"varint,10,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	RetMessage   string         `protobuf:"bytes,11,opt,name=ret_message,json=retMessage,proto3" json:"ret_message,omitempty"`
}

func (x *RespQueryRC20TokenInfo) Reset() {
	*x = RespQueryRC20TokenInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token20_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespQueryRC20TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespQueryRC20TokenInfo) ProtoMessage() {}

func (x *RespQueryRC20TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_token20_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespQueryRC20TokenInfo.ProtoReflect.Descriptor instead.
func (*RespQueryRC20TokenInfo) Descriptor() ([]byte, []int) {
	return file_token20_proto_rawDescGZIP(), []int{6}
}

func (x *RespQueryRC20TokenInfo) GetTokenAddress() []byte {
	if x != nil {
		return x.TokenAddress
	}
	return nil
}

func (x *RespQueryRC20TokenInfo) GetInfo() *TokenRC20Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *RespQueryRC20TokenInfo) GetTokenNonce() int32 {
	if x != nil {
		return x.TokenNonce
	}
	return 0
}

func (x *RespQueryRC20TokenInfo) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *RespQueryRC20TokenInfo) GetRetMessage() string {
	if x != nil {
		return x.RetMessage
	}
	return ""
}

type ReqQueryRC20TokenValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenAddress []byte `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	OwnerAddress []byte `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
}

func (x *ReqQueryRC20TokenValue) Reset() {
	*x = ReqQueryRC20TokenValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token20_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqQueryRC20TokenValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqQueryRC20TokenValue) ProtoMessage() {}

func (x *ReqQueryRC20TokenValue) ProtoReflect() protoreflect.Message {
	mi := &file_token20_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqQueryRC20TokenValue.ProtoReflect.Descriptor instead.
func (*ReqQueryRC20TokenValue) Descriptor() ([]byte, []int) {
	return file_token20_proto_rawDescGZIP(), []int{7}
}

func (x *ReqQueryRC20TokenValue) GetTokenAddress() []byte {
	if x != nil {
		return x.TokenAddress
	}
	return nil
}

func (x *ReqQueryRC20TokenValue) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

type RespQueryRC20TokenValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenAddress string          `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	OwnerAddress string          `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Value        *TokenRC20Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	TotalSupply  string          `protobuf:"bytes,4,opt,name=totalSupply,proto3" json:"totalSupply,omitempty"` //总量
	Name         string          `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Symbol       string          `protobuf:"bytes,6,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals     int64           `protobuf:"varint,7,opt,name=decimals,proto3" json:"decimals,omitempty"` //精度
	RetCode      int32           `protobuf:"varint,10,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	RetMessage   string          `protobuf:"bytes,11,opt,name=ret_message,json=retMessage,proto3" json:"ret_message,omitempty"`
}

func (x *RespQueryRC20TokenValue) Reset() {
	*x = RespQueryRC20TokenValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token20_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespQueryRC20TokenValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespQueryRC20TokenValue) ProtoMessage() {}

func (x *RespQueryRC20TokenValue) ProtoReflect() protoreflect.Message {
	mi := &file_token20_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespQueryRC20TokenValue.ProtoReflect.Descriptor instead.
func (*RespQueryRC20TokenValue) Descriptor() ([]byte, []int) {
	return file_token20_proto_rawDescGZIP(), []int{8}
}

func (x *RespQueryRC20TokenValue) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *RespQueryRC20TokenValue) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *RespQueryRC20TokenValue) GetValue() *TokenRC20Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RespQueryRC20TokenValue) GetTotalSupply() string {
	if x != nil {
		return x.TotalSupply
	}
	return ""
}

func (x *RespQueryRC20TokenValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RespQueryRC20TokenValue) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RespQueryRC20TokenValue) GetDecimals() int64 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *RespQueryRC20TokenValue) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *RespQueryRC20TokenValue) GetRetMessage() string {
	if x != nil {
		return x.RetMessage
	}
	return ""
}

var File_token20_proto protoreflect.FileDescriptor

var file_token20_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x80, 0x03, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x52, 0x43, 0x32, 0x30, 0x12, 0x3b, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x43, 0x32, 0x30,
	0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x30, 0x52, 0x08, 0x66, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x6f, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x03, 0x74, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x22, 0x8f, 0x01, 0x0a, 0x0a, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x30, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x4f, 0x4e, 0x53, 0x54, 0x52, 0x55, 0x43, 0x54,
	0x5f, 0x46, 0x49, 0x58, 0x53, 0x55, 0x50, 0x50, 0x4c, 0x59, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13,
	0x43, 0x4f, 0x4e, 0x53, 0x54, 0x52, 0x55, 0x43, 0x54, 0x5f, 0x50, 0x52, 0x49, 0x4e, 0x54, 0x41,
	0x42, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x46, 0x45,
	0x52, 0x53, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x52, 0x49, 0x4e, 0x54, 0x10, 0x04, 0x12,
	0x08, 0x0a, 0x04, 0x42, 0x55, 0x52, 0x4e, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x44, 0x44,
	0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x53, 0x10, 0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x4d,
	0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x53, 0x10, 0x07, 0x22, 0x5d, 0x0a, 0x0e, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x43, 0x32, 0x30, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x65, 0x78, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0xb5, 0x02, 0x0a, 0x0d, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x43, 0x32, 0x30, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53,
	0x75, 0x70, 0x70, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x08, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x65, 0x78, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x69,
	0x6e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x72,
	0x69, 0x6e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x54, 0x72, 0x69, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x54, 0x72, 0x69, 0x65, 0x52, 0x6f, 0x6f,
	0x74, 0x22, 0x3d, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x43, 0x61, 0x6c, 0x6c, 0x32, 0x30, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x43, 0x32, 0x30, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x66, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x70, 0x43, 0x61, 0x6c, 0x6c, 0x32, 0x30, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x12, 0x19, 0x0a, 0x08,
	0x72, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x74, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3c, 0x0a, 0x15, 0x52, 0x65, 0x71, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x43, 0x32, 0x30, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xc5, 0x01, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x70, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x43, 0x32, 0x30, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x29, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x43, 0x32, 0x30, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6e, 0x6f, 0x6e, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4e, 0x6f, 0x6e,
	0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x72, 0x65, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x62,
	0x0a, 0x16, 0x52, 0x65, 0x71, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x43, 0x32, 0x30, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x23, 0x0a,
	0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0xb7, 0x02, 0x0a, 0x17, 0x52, 0x65, 0x73, 0x70, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x43, 0x32, 0x30, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x43, 0x32, 0x30, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53,
	0x75, 0x70, 0x70, 0x6c, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73,
	0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72,
	0x65, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x72, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_token20_proto_rawDescOnce sync.Once
	file_token20_proto_rawDescData = file_token20_proto_rawDesc
)

func file_token20_proto_rawDescGZIP() []byte {
	file_token20_proto_rawDescOnce.Do(func() {
		file_token20_proto_rawDescData = protoimpl.X.CompressGZIP(file_token20_proto_rawDescData)
	})
	return file_token20_proto_rawDescData
}

var file_token20_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_token20_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_token20_proto_goTypes = []interface{}{
	(ContractRC20_Function20)(0),    // 0: entity.ContractRC20.Function20
	(*ContractRC20)(nil),            // 1: entity.ContractRC20
	(*TokenRC20Value)(nil),          // 2: entity.TokenRC20Value
	(*TokenRC20Info)(nil),           // 3: entity.TokenRC20Info
	(*ReqCall20Contract)(nil),       // 4: entity.ReqCall20Contract
	(*RespCall20Contract)(nil),      // 5: entity.RespCall20Contract
	(*ReqQueryRC20TokenInfo)(nil),   // 6: entity.ReqQueryRC20TokenInfo
	(*RespQueryRC20TokenInfo)(nil),  // 7: entity.RespQueryRC20TokenInfo
	(*ReqQueryRC20TokenValue)(nil),  // 8: entity.ReqQueryRC20TokenValue
	(*RespQueryRC20TokenValue)(nil), // 9: entity.RespQueryRC20TokenValue
}
var file_token20_proto_depIdxs = []int32{
	0, // 0: entity.ContractRC20.function:type_name -> entity.ContractRC20.Function20
	1, // 1: entity.ReqCall20Contract.data:type_name -> entity.ContractRC20
	3, // 2: entity.RespQueryRC20TokenInfo.info:type_name -> entity.TokenRC20Info
	2, // 3: entity.RespQueryRC20TokenValue.value:type_name -> entity.TokenRC20Value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_token20_proto_init() }
func file_token20_proto_init() {
	if File_token20_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_token20_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractRC20); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token20_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenRC20Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token20_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenRC20Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token20_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqCall20Contract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token20_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespCall20Contract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token20_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqQueryRC20TokenInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token20_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespQueryRC20TokenInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token20_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqQueryRC20TokenValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token20_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespQueryRC20TokenValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_token20_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_token20_proto_goTypes,
		DependencyIndexes: file_token20_proto_depIdxs,
		EnumInfos:         file_token20_proto_enumTypes,
		MessageInfos:      file_token20_proto_msgTypes,
	}.Build()
	File_token20_proto = out.File
	file_token20_proto_rawDesc = nil
	file_token20_proto_goTypes = nil
	file_token20_proto_depIdxs = nil
}
