// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: transaction.proto

package entity

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TransactionType int32

const (
	TransactionType_NORMAL         TransactionType = 0
	TransactionType_MULI_SIGN      TransactionType = 1
	TransactionType_RC20_CONTRACT  TransactionType = 2
	TransactionType_RC721_CONTRACT TransactionType = 3
	TransactionType_CVM_CONTRACT   TransactionType = 4
	TransactionType_JSVM_CONTRACT  TransactionType = 5
	TransactionType_EVFS_CONTRACT  TransactionType = 6 //evfs
	TransactionType_CHAIN_CONFIG   TransactionType = 255
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0:   "NORMAL",
		1:   "MULI_SIGN",
		2:   "RC20_CONTRACT",
		3:   "RC721_CONTRACT",
		4:   "CVM_CONTRACT",
		5:   "JSVM_CONTRACT",
		6:   "EVFS_CONTRACT",
		255: "CHAIN_CONFIG",
	}
	TransactionType_value = map[string]int32{
		"NORMAL":         0,
		"MULI_SIGN":      1,
		"RC20_CONTRACT":  2,
		"RC721_CONTRACT": 3,
		"CVM_CONTRACT":   4,
		"JSVM_CONTRACT":  5,
		"EVFS_CONTRACT":  6,
		"CHAIN_CONFIG":   255,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_transaction_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

//函数操作类型：{
//1.construct(address managers[],int voteCount) public returns (bool);创建合约
//2.addManagers(address to[],int voteCount);
//3.rmManagers(address to[]),int voteCount);
//}
type ContractMultiSig_FunctionMultiSig int32

const (
	ContractMultiSig_UNKNOW      ContractMultiSig_FunctionMultiSig = 0
	ContractMultiSig_CONSTRUCT   ContractMultiSig_FunctionMultiSig = 1
	ContractMultiSig_ADDMANAGERS ContractMultiSig_FunctionMultiSig = 2
	ContractMultiSig_RMMANAGERS  ContractMultiSig_FunctionMultiSig = 3
)

// Enum value maps for ContractMultiSig_FunctionMultiSig.
var (
	ContractMultiSig_FunctionMultiSig_name = map[int32]string{
		0: "UNKNOW",
		1: "CONSTRUCT",
		2: "ADDMANAGERS",
		3: "RMMANAGERS",
	}
	ContractMultiSig_FunctionMultiSig_value = map[string]int32{
		"UNKNOW":      0,
		"CONSTRUCT":   1,
		"ADDMANAGERS": 2,
		"RMMANAGERS":  3,
	}
)

func (x ContractMultiSig_FunctionMultiSig) Enum() *ContractMultiSig_FunctionMultiSig {
	p := new(ContractMultiSig_FunctionMultiSig)
	*p = x
	return p
}

func (x ContractMultiSig_FunctionMultiSig) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContractMultiSig_FunctionMultiSig) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_proto_enumTypes[1].Descriptor()
}

func (ContractMultiSig_FunctionMultiSig) Type() protoreflect.EnumType {
	return &file_transaction_proto_enumTypes[1]
}

func (x ContractMultiSig_FunctionMultiSig) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContractMultiSig_FunctionMultiSig.Descriptor instead.
func (ContractMultiSig_FunctionMultiSig) EnumDescriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{2, 0}
}

type TransactionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash            string             `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Body            *TransactionBody   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Signature       string             `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Status          *TransactionStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` //@deprecated,status apply in result trie
	Node            *TransactionNode   `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	Accepttimestamp int64              `protobuf:"varint,6,opt,name=accepttimestamp,proto3" json:"accepttimestamp,omitempty"`
}

func (x *TransactionInfo) Reset() {
	*x = TransactionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInfo) ProtoMessage() {}

func (x *TransactionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInfo.ProtoReflect.Descriptor instead.
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionInfo) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *TransactionInfo) GetBody() *TransactionBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *TransactionInfo) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *TransactionInfo) GetStatus() *TransactionStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TransactionInfo) GetNode() *TransactionNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *TransactionInfo) GetAccepttimestamp() int64 {
	if x != nil {
		return x.Accepttimestamp
	}
	return 0
}

type TransactionBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce         int32                `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Address       string               `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Outputs       []*TransactionOutput `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	FeeHi         int64                `protobuf:"varint,4,opt,name=fee_hi,json=feeHi,proto3" json:"fee_hi,omitempty"`                         //手续费高位
	FeeLow        int64                `protobuf:"varint,5,opt,name=fee_low,json=feeLow,proto3" json:"fee_low,omitempty"`                      //手续费低位;
	InnerCodetype int32                `protobuf:"varint,6,opt,name=inner_codetype,json=innerCodetype,proto3" json:"inner_codetype,omitempty"` //内置指令交易[0=普通交易,1=多重签名交易,2=RC20交易，3=RC721交易，4=CVM合约调用,5=JSVM合约调用,6=evfs交易,7=链委员会,8=链管理员组
	CodeData      string               `protobuf:"bytes,7,opt,name=code_data,json=codeData,proto3" json:"code_data,omitempty"`                 //指令数据
	ExtData       string               `protobuf:"bytes,8,opt,name=ext_data,json=extData,proto3" json:"ext_data,omitempty"`
	Timestamp     int64                `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BizCode       string               `protobuf:"bytes,10,opt,name=biz_code,json=bizCode,proto3" json:"biz_code,omitempty"` //业务代码
	Version       string               `protobuf:"bytes,11,opt,name=version,proto3" json:"version,omitempty"`                //版本
	ChainId       int32                `protobuf:"varint,12,opt,name=chainId,proto3" json:"chainId,omitempty"`
	SysId         string               `protobuf:"bytes,13,opt,name=sys_id,json=sysId,proto3" json:"sys_id,omitempty"`
}

func (x *TransactionBody) Reset() {
	*x = TransactionBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionBody) ProtoMessage() {}

func (x *TransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionBody.ProtoReflect.Descriptor instead.
func (*TransactionBody) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionBody) GetNonce() int32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *TransactionBody) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TransactionBody) GetOutputs() []*TransactionOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *TransactionBody) GetFeeHi() int64 {
	if x != nil {
		return x.FeeHi
	}
	return 0
}

func (x *TransactionBody) GetFeeLow() int64 {
	if x != nil {
		return x.FeeLow
	}
	return 0
}

func (x *TransactionBody) GetInnerCodetype() int32 {
	if x != nil {
		return x.InnerCodetype
	}
	return 0
}

func (x *TransactionBody) GetCodeData() string {
	if x != nil {
		return x.CodeData
	}
	return ""
}

func (x *TransactionBody) GetExtData() string {
	if x != nil {
		return x.ExtData
	}
	return ""
}

func (x *TransactionBody) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionBody) GetBizCode() string {
	if x != nil {
		return x.BizCode
	}
	return ""
}

func (x *TransactionBody) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TransactionBody) GetChainId() int32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *TransactionBody) GetSysId() string {
	if x != nil {
		return x.SysId
	}
	return ""
}

type ContractMultiSig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Function ContractMultiSig_FunctionMultiSig `protobuf:"varint,1,opt,name=function,proto3,enum=entity.ContractMultiSig_FunctionMultiSig" json:"function,omitempty"` //
	Managers []string                          `protobuf:"bytes,2,rep,name=managers,proto3" json:"managers,omitempty"`
	ExtDatas string                            `protobuf:"bytes,3,opt,name=ext_datas,json=extDatas,proto3" json:"ext_datas,omitempty"` //扩展信息
	Name     string                            `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                         //构建函数时候使用
	Symbol   string                            `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`                     //构建函数时候使用
	MinVote  int32                             `protobuf:"varint,6,opt,name=min_vote,json=minVote,proto3" json:"min_vote,omitempty"`   //最少几个人投票
}

func (x *ContractMultiSig) Reset() {
	*x = ContractMultiSig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractMultiSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractMultiSig) ProtoMessage() {}

func (x *ContractMultiSig) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractMultiSig.ProtoReflect.Descriptor instead.
func (*ContractMultiSig) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *ContractMultiSig) GetFunction() ContractMultiSig_FunctionMultiSig {
	if x != nil {
		return x.Function
	}
	return ContractMultiSig_UNKNOW
}

func (x *ContractMultiSig) GetManagers() []string {
	if x != nil {
		return x.Managers
	}
	return nil
}

func (x *ContractMultiSig) GetExtDatas() string {
	if x != nil {
		return x.ExtDatas
	}
	return ""
}

func (x *ContractMultiSig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContractMultiSig) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ContractMultiSig) GetMinVote() int32 {
	if x != nil {
		return x.MinVote
	}
	return 0
}

type PBMultsigAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Creator  string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Managers []string `protobuf:"bytes,2,rep,name=managers,proto3" json:"managers,omitempty"`
	MinVote  int32    `protobuf:"varint,3,opt,name=min_vote,json=minVote,proto3" json:"min_vote,omitempty"` //至少多少个人签名
}

func (x *PBMultsigAccount) Reset() {
	*x = PBMultsigAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBMultsigAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBMultsigAccount) ProtoMessage() {}

func (x *PBMultsigAccount) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBMultsigAccount.ProtoReflect.Descriptor instead.
func (*PBMultsigAccount) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *PBMultsigAccount) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *PBMultsigAccount) GetManagers() []string {
	if x != nil {
		return x.Managers
	}
	return nil
}

func (x *PBMultsigAccount) GetMinVote() int32 {
	if x != nil {
		return x.MinVote
	}
	return 0
}

type TransactionOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address     string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount      string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Token       string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	TokenAmount string   `protobuf:"bytes,4,opt,name=tokenAmount,proto3" json:"tokenAmount,omitempty"`
	Symbol      string   `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	CryptoToken []string `protobuf:"bytes,6,rep,name=cryptoToken,proto3" json:"cryptoToken,omitempty"`
}

func (x *TransactionOutput) Reset() {
	*x = TransactionOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionOutput) ProtoMessage() {}

func (x *TransactionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionOutput.ProtoReflect.Descriptor instead.
func (*TransactionOutput) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionOutput) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TransactionOutput) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransactionOutput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TransactionOutput) GetTokenAmount() string {
	if x != nil {
		return x.TokenAmount
	}
	return ""
}

func (x *TransactionOutput) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TransactionOutput) GetCryptoToken() []string {
	if x != nil {
		return x.CryptoToken
	}
	return nil
}

type TransactionNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nid     string `protobuf:"bytes,1,opt,name=nid,proto3" json:"nid,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *TransactionNode) Reset() {
	*x = TransactionNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionNode) ProtoMessage() {}

func (x *TransactionNode) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionNode.ProtoReflect.Descriptor instead.
func (*TransactionNode) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionNode) GetNid() string {
	if x != nil {
		return x.Nid
	}
	return ""
}

func (x *TransactionNode) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type TransactionStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Result    string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Hash      string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Height    int64  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	//support for eth like chain client
	Logs              []string `protobuf:"bytes,6,rep,name=logs,proto3" json:"logs,omitempty"`
	LogsBloom         string   `protobuf:"bytes,7,opt,name=logsBloom,proto3" json:"logsBloom,omitempty"`
	BlockIndex        int32    `protobuf:"varint,8,opt,name=blockIndex,proto3" json:"blockIndex,omitempty"`
	GasUsed           string   `protobuf:"bytes,9,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	CumulativeGasUsed string   `protobuf:"bytes,10,opt,name=cumulativeGasUsed,proto3" json:"cumulativeGasUsed,omitempty"`
	ContractAddress   string   `protobuf:"bytes,11,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
}

func (x *TransactionStatus) Reset() {
	*x = TransactionStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStatus) ProtoMessage() {}

func (x *TransactionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStatus.ProtoReflect.Descriptor instead.
func (*TransactionStatus) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *TransactionStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransactionStatus) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *TransactionStatus) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *TransactionStatus) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TransactionStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionStatus) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *TransactionStatus) GetLogsBloom() string {
	if x != nil {
		return x.LogsBloom
	}
	return ""
}

func (x *TransactionStatus) GetBlockIndex() int32 {
	if x != nil {
		return x.BlockIndex
	}
	return 0
}

func (x *TransactionStatus) GetGasUsed() string {
	if x != nil {
		return x.GasUsed
	}
	return ""
}

func (x *TransactionStatus) GetCumulativeGasUsed() string {
	if x != nil {
		return x.CumulativeGasUsed
	}
	return ""
}

func (x *TransactionStatus) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

type BroadcastTransactionMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxHash  []string `protobuf:"bytes,1,rep,name=txHash,proto3" json:"txHash,omitempty"`
	TxDatas []string `protobuf:"bytes,2,rep,name=txDatas,proto3" json:"txDatas,omitempty"`
}

func (x *BroadcastTransactionMsg) Reset() {
	*x = BroadcastTransactionMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastTransactionMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastTransactionMsg) ProtoMessage() {}

func (x *BroadcastTransactionMsg) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastTransactionMsg.ProtoReflect.Descriptor instead.
func (*BroadcastTransactionMsg) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *BroadcastTransactionMsg) GetTxHash() []string {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *BroadcastTransactionMsg) GetTxDatas() []string {
	if x != nil {
		return x.TxDatas
	}
	return nil
}

var File_transaction_proto protoreflect.FileDescriptor

var file_transaction_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0xfa, 0x01, 0x0a, 0x0f,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x12, 0x2b, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x31,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x2b, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x28,
	0x0a, 0x0f, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x89, 0x03, 0x0a, 0x0f, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x33, 0x0a, 0x07,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x73, 0x12, 0x15, 0x0a, 0x06, 0x66, 0x65, 0x65, 0x5f, 0x68, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x66, 0x65, 0x65, 0x48, 0x69, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x65, 0x65, 0x5f,
	0x6c, 0x6f, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x65, 0x65, 0x4c, 0x6f,
	0x77, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x69, 0x6e, 0x6e, 0x65, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x64, 0x65,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x64,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x78, 0x74, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x19,
	0x0a, 0x08, 0x62, 0x69, 0x7a, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x62, 0x69, 0x7a, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x73, 0x79, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x79, 0x73, 0x49, 0x64, 0x22, 0xa9, 0x02, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x69, 0x67, 0x12, 0x45, 0x0a, 0x08, 0x66, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x53, 0x69, 0x67, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x53, 0x69, 0x67, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x65, 0x78, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x5f, 0x76, 0x6f, 0x74,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x56, 0x6f, 0x74, 0x65,
	0x22, 0x4e, 0x0a, 0x10, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x53, 0x69, 0x67, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4e, 0x53, 0x54, 0x52, 0x55, 0x43, 0x54, 0x10, 0x01, 0x12,
	0x0f, 0x0a, 0x0b, 0x41, 0x44, 0x44, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x53, 0x10, 0x02,
	0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x4d, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x53, 0x10, 0x03,
	0x22, 0x63, 0x0a, 0x10, 0x50, 0x42, 0x4d, 0x75, 0x6c, 0x74, 0x73, 0x69, 0x67, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x69,
	0x6e, 0x5f, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x69,
	0x6e, 0x56, 0x6f, 0x74, 0x65, 0x22, 0xb7, 0x01, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x20, 0x0a,
	0x0b, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x3d, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6e, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xd1,
	0x02, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f,
	0x67, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x73, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x73, 0x42, 0x6c, 0x6f, 0x6f, 0x6d,
	0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x18, 0x0a, 0x07, 0x67, 0x61, 0x73, 0x55, 0x73, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x67, 0x61, 0x73, 0x55, 0x73, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x63, 0x75,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x47, 0x61, 0x73, 0x55, 0x73, 0x65, 0x64, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x76,
	0x65, 0x47, 0x61, 0x73, 0x55, 0x73, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x4b, 0x0a, 0x17, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x78, 0x44, 0x61, 0x74, 0x61, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74, 0x78, 0x44, 0x61, 0x74, 0x61, 0x73, 0x2a,
	0x9e, 0x01, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12,
	0x0d, 0x0a, 0x09, 0x4d, 0x55, 0x4c, 0x49, 0x5f, 0x53, 0x49, 0x47, 0x4e, 0x10, 0x01, 0x12, 0x11,
	0x0a, 0x0d, 0x52, 0x43, 0x32, 0x30, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x41, 0x43, 0x54, 0x10,
	0x02, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x43, 0x37, 0x32, 0x31, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52,
	0x41, 0x43, 0x54, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x56, 0x4d, 0x5f, 0x43, 0x4f, 0x4e,
	0x54, 0x52, 0x41, 0x43, 0x54, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x4a, 0x53, 0x56, 0x4d, 0x5f,
	0x43, 0x4f, 0x4e, 0x54, 0x52, 0x41, 0x43, 0x54, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x56,
	0x46, 0x53, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x41, 0x43, 0x54, 0x10, 0x06, 0x12, 0x11, 0x0a,
	0x0c, 0x43, 0x48, 0x41, 0x49, 0x4e, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x10, 0xff, 0x01,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData = file_transaction_proto_rawDesc
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_transaction_proto_rawDescData)
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_transaction_proto_goTypes = []interface{}{
	(TransactionType)(0),                   // 0: entity.TransactionType
	(ContractMultiSig_FunctionMultiSig)(0), // 1: entity.ContractMultiSig.FunctionMultiSig
	(*TransactionInfo)(nil),                // 2: entity.TransactionInfo
	(*TransactionBody)(nil),                // 3: entity.TransactionBody
	(*ContractMultiSig)(nil),               // 4: entity.ContractMultiSig
	(*PBMultsigAccount)(nil),               // 5: entity.PBMultsigAccount
	(*TransactionOutput)(nil),              // 6: entity.TransactionOutput
	(*TransactionNode)(nil),                // 7: entity.TransactionNode
	(*TransactionStatus)(nil),              // 8: entity.TransactionStatus
	(*BroadcastTransactionMsg)(nil),        // 9: entity.BroadcastTransactionMsg
}
var file_transaction_proto_depIdxs = []int32{
	3, // 0: entity.TransactionInfo.body:type_name -> entity.TransactionBody
	8, // 1: entity.TransactionInfo.status:type_name -> entity.TransactionStatus
	7, // 2: entity.TransactionInfo.node:type_name -> entity.TransactionNode
	6, // 3: entity.TransactionBody.outputs:type_name -> entity.TransactionOutput
	1, // 4: entity.ContractMultiSig.function:type_name -> entity.ContractMultiSig.FunctionMultiSig
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractMultiSig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBMultsigAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastTransactionMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transaction_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		EnumInfos:         file_transaction_proto_enumTypes,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_rawDesc = nil
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
